import {
  CalendarDotIcon,
  EnvelopeIcon,
  GithubLogoIcon,
  LinkedinLogoIcon,
  ReadCvLogoIcon,
} from "@phosphor-icons/react/ssr";

export const LINKS = [
  { name: "CV", href: "/cv", newTab: false, icon: ReadCvLogoIcon },
  {
    name: "GitHub",
    href: "https://github.com/richardsolomou",
    newTab: true,
    icon: GithubLogoIcon,
  },
  {
    name: "LinkedIn",
    href: "https://linkedin.com/in/richardsolomou",
    newTab: true,
    icon: LinkedinLogoIcon,
  },
  {
    name: "Email",
    href: "mailto:richard@solomou.dev",
    newTab: false,
    icon: EnvelopeIcon,
  },
  {
    name: "Schedule",
    href: "https://cal.com/richardsolomou/30min",
    newTab: true,
    icon: CalendarDotIcon,
  },
];

export const STACK = {
  Frontend: {
    visible: [
      "React",
      "Next.js",
      "TypeScript",
      "TanStack Start",
      "Tailwind CSS",
    ],
    hidden: [
      "Vite",
      "TanStack Query",
      "Zustand",
      "Material UI",
      "React Hook Form",
      "Zod",
      "Motion",
    ],
  },
  Backend: {
    visible: [
      "Node.js",
      "PostgreSQL",
      "Drizzle",
      "Stripe",
      "Convex",
      "Better Auth",
    ],
    hidden: [
      "tRPC",
      "Prisma",
      "NestJS",
      "Redis",
      "Socket.io",
      "WebSockets",
      "REST APIs",
    ],
  },
  "Dev Tools": {
    visible: [
      "VS Code",
      "Git",
      "pnpm",
      "Turborepo",
      "GitHub Actions",
      "Vitest",
    ],
    hidden: ["Biome", "Playwright", "ESLint", "Prettier"],
  },
  "Cloud & Infrastructure": {
    visible: ["Vercel", "AWS", "Cloudflare", "Docker", "Kubernetes"],
    hidden: ["Azure", "GCP", "Helm", "Terraform"],
  },
  "Monitoring & Analytics": {
    visible: ["PostHog", "Sentry"],
    hidden: ["Grafana", "Prometheus"],
  },
};

export const EXPERIENCE = [
  {
    id: "technical-lead-keenious",
    title: "Technical Lead",
    company: "Keenious",
    companyUrl: "https://keenious.com",
    companyIcon: "/images/logos/keenious.webp",
    companyIconPrint: "/images/logos/keenious.webp",
    location: "Tromsø, Norway (Remote)",
    period: "January 2023 - Present",
    description: [
      "Architected and implemented innovative features using Next.js, NestJS, TypeScript, and PostgreSQL.",
      "Orchestrated Kubernetes infrastructure on AWS and Azure, and streamlined local development with Docker.",
      "Led development of complete AI-powered research assistant stack for enhanced article discovery.",
      "Spearheaded end-to-end testing implementation and system optimization for performance and scalability.",
    ],
  },
  {
    id: "creator-tarrasque",
    title: "Founder (acquired)",
    company: "Tarrasque.io",
    companyUrl: "https://tarrasque.io",
    companyIcon: "/images/logos/tarrasqueio.webp",
    location: "Nicosia, Cyprus",
    period: "July 2020 - January 2025",
    description: [
      "Founded and led a B2C SaaS product serving 9,000+ users worldwide.",
      "Built full-stack features using Next.js, NestJS, TypeScript, WebGL, and real-time WebSocket/GraphQL integrations.",
      "Established CI/CD pipelines and led community building, marketing, and user experience initiatives.",
    ],
  },
  {
    id: "front-end-engineer-keenious",
    title: "Front-End Engineer",
    company: "Keenious",
    companyUrl: "https://keenious.com",
    companyIcon: "/images/logos/keenious.webp",
    location: "Tromsø, Norway (Remote)",
    period: "January 2021 - January 2023",
    description: [
      "Built EdTech Microsoft Word add-in features using React, MobX, and Material UI with legacy browser support.",
      "Led migration to GitHub Actions for automated CI/CD pipelines and delivered performance optimizations.",
    ],
  },
  {
    id: "front-end-software-engineer-proto",
    title: "Front End Software Engineer",
    company: "Proto.io & Overflow.io",
    companyUrl: "https://proto.io",
    location: "Nicosia, Cyprus",
    period: "August 2018 - January 2021",
    description: [
      "Led React/Webpack migration for the main SaaS product and implemented comprehensive Jest testing suite.",
      "Established code standards, CI/CD pipelines through Azure, and mentored junior developers.",
      "Served as Agile advocate while delivering performance improvements and scalability solutions.",
    ],
  },
  {
    id: "senior-front-end-developer-alliants",
    title: "Senior Front End Developer",
    company: "Alliants",
    companyUrl: "https://alliants.com",
    location: "Southampton, United Kingdom",
    period: "March 2018 - June 2018",
    description: [
      "Developed React/Redux applications with comprehensive Jest testing and performance optimizations.",
    ],
  },
  {
    id: "senior-front-end-developer-efficio",
    title: "Senior Front End Developer",
    company: "Efficio Digital",
    companyUrl: "https://efficio.digital",
    location: "Southampton, United Kingdom",
    period: "June 2016 - March 2018",
    description: [
      "Architected scalable front-end applications and reusable component packages as technical subject matter expert.",
      "Established unified design systems, coding standards, and provided developer training and consultation.",
    ],
  },
  {
    id: "ui-ux-developer-feefo",
    title: "UI/UX Developer",
    company: "Feefo",
    companyUrl: "https://feefo.com",
    location: "Petersfield, United Kingdom",
    period: "April 2015 - June 2016",
    description: [
      "Developed SaaS platform features in Agile environment with focus on design collaboration and system optimization.",
    ],
  },
  {
    id: "web-developer-placement-university-of-portsmouth",
    title: "Web Developer (Placement)",
    company: "University of Portsmouth",
    companyUrl: "https://port.ac.uk",
    location: "Portsmouth, United Kingdom",
    period: "July 2013 - July 2014",
    description: [
      "Developed full-stack applications, RESTful APIs, and self-service platform for students and staff.",
    ],
  },
  {
    id: "web-developer-intern-snq-digital",
    title: "Web Developer (Intern)",
    company: "SNQ Digital",
    companyUrl: "https://snqdigital.com",
    location: "Nicosia, Cyprus",
    period: "July 2012 - September 2012",
    description: [
      "Created responsive websites using CSS3 and jQuery, contributed to client projects and design prototypes.",
    ],
  },
  // {
  //   id: "web-developer-intern-netquest",
  //   title: "Web Developer (Intern)",
  //   company: "Netquest",
  //   companyUrl: "https://netquest.cy",
  //   location: "Nicosia, Cyprus",
  //   period: "June 2008 - August 2008",
  //   description: [
  //     "Performed QA testing, created website layouts in Photoshop, and developed sites using HTML/CSS.",
  //   ],
  // },
];

export const EDUCATION = {
  degree: "BSc (Hons) Computer Science (2:1)",
  university: "University of Portsmouth",
  period: "September 2011 - June 2015",
  location: "Portsmouth, United Kingdom",
  achievements: [
    "Developed an NFC-assisted student attendance monitoring system using AngularJS, Node.js, and MySQL",
    "Represented university at Cisco University Challenge hackathon",
    "Focused on web technologies, data structures and algorithms, functional programming, as well as neural networks and genetic algorithms",
  ],
};

export const SKILLS = {
  Languages: ["TypeScript", "JavaScript", "Python", "SQL"],
  Frontend: [
    "React",
    "Next.js",
    "TanStack Start",
    "Tailwind CSS",
    "Vite",
    "TanStack Query",
    "Zustand",
    "Material UI",
    "React Hook Form",
    "Zod",
    "Motion",
    "Figma",
  ],
  Backend: [
    "Node.js",
    "PostgreSQL",
    "Drizzle",
    "Stripe",
    "Convex",
    "Better Auth",
    "tRPC",
    "Prisma",
    "NestJS",
    "FastAPI",
    "Redis",
    "Socket.io",
    "WebSockets",
    "REST APIs",
  ],
  "Dev Tools": [
    "VS Code",
    "Git",
    "pnpm",
    "Turborepo",
    "GitHub Actions",
    "Vitest",
    "Biome",
    "Playwright",
    "ESLint",
    "Prettier",
  ],
  "Cloud & Infrastructure": [
    "Vercel",
    "AWS",
    "Cloudflare",
    "Docker",
    "Kubernetes",
    "Azure",
    "GCP",
    "Helm",
    "Terraform",
  ],
  "Monitoring & Analytics": ["PostHog", "Sentry", "Grafana", "Prometheus"],
  Other: ["DDD", "SOA", "TDD", "OOP", "Agile (Scrum, Kanban)"],
};
